### ISSUE TITLE
logtypy filter in site24ｘ7

### ISSUE THREAD

**Issue by zeoYi** [site24x7/fluent-plugin-site24x7#1]

**Comment by zeoYi** [comment]
**i use fluent-plugin-site24x7 to upload logs to site24x7 ,when i create logtype without filters on site24x7, logs can be  uploaded  to site24x7,, but when i create logtype with filters on site24x7, logs cannot be  uploaded  to site24x7, the fluentd logs are below:**

`2021-12-22 11:40:46 +0900 [debug]: #0 [site24x7_agent] pattern not matched regex : (?-mix:^(?<Datetime>((20)\d{2}\-(0[1-9]|1[0-2])\-(0[1-9]|[1-2][0-9]|30|31)T([0-1][0-9]|2[0-3])\:([0-5][0-9])\:([0-5][0-9]|60)([+-]\d{1,2}\:\d{1,2})))\s{7,}(?<server>(passport.ERROR))\s{3,}(?<msg>(STATUS|NG))) and received line : 2021-12-22T11:40:45+09:00       passport.WARN   {timestamp:1639632803,unique:61bacfa3500d47519,STATUS:NA,user_seqックしました。,KEY:[]}},context:[],extra:[]}`

**Comment by zeoYi** [comment]
when i add filter to JSON log type ,then error occur below 
<2021-12-27 19:33:52 +0900 [error]: #0 [site24x7_agen_1] Exception ["/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-site24x7-0.1.3/lib/fluent/plugin/out_site24x7.rb:172:in `block in is_filters_matched'", "/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-site24x7-0.1.3/lib/fluent/plugin/out_site24x7.rb:171:in `each'", "/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-site24x7-0.1.3/lib/fluent/plugin/out_site24x7.rb:171:in `is_filters_matched'", "/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-site24x7-0.1.3/lib/fluent/plugin/out_site24x7.rb:221:in `block in json_log_parser'", "/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-site24x7-0.1.3/lib/fluent/plugin/out_site24x7.rb:209:in `each'", "/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-site24x7-0.1.3/lib/fluent/plugin/out_site24x7.rb:209:in `json_log_parser'", "/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-site24x7-0.1.3/lib/fluent/plugin/out_site24x7.rb:288:in `format_http_event_batch'", "/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-site24x7-0.1.3/lib/fluent/plugin/out_site24x7.rb:254:in `block in process_http_events'", "/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-site24x7-0.1.3/lib/fluent/plugin/out_site24x7.rb:253:in `each'", "/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-site24x7-0.1.3/lib/fluent/plugin/out_site24x7.rb:253:in `process_http_events'", "/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-site24x7-0.1.3/lib/fluent/plugin/out_site24x7.rb:245:in `write'", "/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/output.rb:1138:in `try_flush'", "/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/output.rb:1450:in `flush_thread_run'", "/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin/output.rb:462:in `block (2 levels) in start'", "/opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.12.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'"]>
